import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ConfigModule } from '../../shared/components/config/config.module';
import { Observable } from 'rxjs';

const productlist: any = [
    'Almond',
    'Amla',
    'Anise',
    'Apple',
    'Areca nut',
    'Arhar',
    'Bajra',
    'Bamboo',
    'Banana',
    '   Barley',
    '   Basmati Rice',
    '   Beetroot',
    '   Betel leaves',
    '   Okra',
    '   Bitter gourd',
    '   Bottle gourd',
    '   Brinjal',
    '   Broccoli',
    '   Buck Wheat',
    '   Cabbage',
    '   Capsicum',
    '   Carnation',
    '   Carrots',
    '   Castor seed',
    '   Cauliflower',
    '   Chana whole',
    '   Chickpeas',
    '   Chicory',
    '   Cluster beans',
    '   Coconut',
    '   Coffee',
    '   Colocasia vegetable',
    '   Coriander leaves',
    '   Coriander whole',
    '   Cotton',
    '   Cotton Seed',
    '   Cucumber',
    '   Cumin',
    '   Custard apple',
    '   Dried Raw Mango Slices',
    '   Drumstick',
    '   Dry Ginger',
    '   Fennel seed',
    '   Fenugreek leaves',
    '   Fenugreek seed',
    '   Garlic',
    '   Ginger',
    '   Gladiolus',
    '   Grapes',
    '   Green Peas',
    '   Green chillies',
    '   Groundnut with pods',
    '   Guar Seed',
    '   Guava',
    '   Horse Gram',
    '   Isabgol',
    '   Ivy gourd',
    '   Jackfruit',
    '   Jaggery',
    '   Jimikand(Suran)',
    '   Jowar',
    '   Kinnow',
    '   Kusum seed',
    '   Large cardamom',
    '   Lemon',
    '   Lentil',
    '   Lettuce',
    '   Linseed',
    '   Litchi',
    '   Lobia',
    '   Mahua flower',
    '   Mahua seed',
    '   Maize',
    '   Mango',
    '   Marigold',
    '   Masoor whole',
    '   Moong whole',
    '   Moth',
    '   Mushrooms',
    '   Musk melon',
    '   Mustard leaf',
    '   Mustard seed',
    '   Niger Seed',
    '   Nutmeg',
    '   Onion',
    '   Orange',
    '   Paddy',
    '   Papaya',
    '   Pea',
    '   Peach',
    '   Peanut kernel',
    '   Pear',
    '   Pigeon Peas',
    '   Pineapple',
    '   Plum',
    '   Pointed gourd',
    '   Pomegranate',
    '   Pongam seeds',
    '   Potato',
    '   Pumpkin',
    '   Ragi',
    '   Raisins',
    '   Rajma',
    '   Raw Cashew nut',
    '   Raw Jute',
    '   Raw Mango for pickles',
    '   Red chilli',
    '   Reddish',
    '   Ribbed celery',
    '   Ridge Gourd',
    '   Rittha',
    '   SEM',
    '   Safflower seeds',
    '   Saffron',
    '   Sal Seed',
    '   Sapota',
    '   Sesame seed',
    '   Snake Gourd',
    '   Sorghum',
    '   Soyabean',
    '   Spinach',
    '   Squashes',
    '   Strawberries',
    '   Sugarcane',
    '   Sunflower seed',
    '   Sweet Corn',
    '   Sweet orange',
    '   Sweet potato',
    '   Tamarind',
    '   Tejpata',
    '   Tender coconut',
    '   Tomato',
    '   Tuberose',
    '   Turmeric',
    '   Urad whole',
    '   Watermelon',
    '   Wheat',
    '   White Peas'
];


@Injectable()
export class SalesService {
    constructor(private httpClient: HttpClient, private config: ConfigModule) { }
    getprod(): Observable<any> {
        return productlist;
    }
}
